// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn4FCVgS5kIITJIodRO0itB22zvyjMTqk',
    appId: '1:1096770483496:web:5897db3aebbbbcde8bcc1d',
    messagingSenderId: '1096770483496',
    projectId: 'books-fa96f',
    authDomain: 'books-fa96f.firebaseapp.com',
    storageBucket: 'books-fa96f.appspot.com',
    measurementId: 'G-0N9MPMT6R0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcTTnDS6CWv_Bnwg7nhyRzU3HmSHS7p-k',
    appId: '1:1096770483496:android:8cfad7ebf93ccd1c8bcc1d',
    messagingSenderId: '1096770483496',
    projectId: 'books-fa96f',
    storageBucket: 'books-fa96f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnDtA9LkiDJ007Ls3xEtl06vF6ZWGWZxk',
    appId: '1:1096770483496:ios:879ae22e52cd71638bcc1d',
    messagingSenderId: '1096770483496',
    projectId: 'books-fa96f',
    storageBucket: 'books-fa96f.appspot.com',
    iosBundleId: 'com.example.bookStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnDtA9LkiDJ007Ls3xEtl06vF6ZWGWZxk',
    appId: '1:1096770483496:ios:879ae22e52cd71638bcc1d',
    messagingSenderId: '1096770483496',
    projectId: 'books-fa96f',
    storageBucket: 'books-fa96f.appspot.com',
    iosBundleId: 'com.example.bookStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn4FCVgS5kIITJIodRO0itB22zvyjMTqk',
    appId: '1:1096770483496:web:b62af1ff3ab5c18e8bcc1d',
    messagingSenderId: '1096770483496',
    projectId: 'books-fa96f',
    authDomain: 'books-fa96f.firebaseapp.com',
    storageBucket: 'books-fa96f.appspot.com',
    measurementId: 'G-XC7YRY0NG0',
  );
}
